### ISSUE TITLE
Interface mobile 

### ISSUE THREAD

**Issue by AlexPernot** [romainchalut/MT5_FirefoxOS#1]
Discutons ici de nos idées pour la nouvelle interface.

**Comment by AlexPernot** [comment]
Je balance quelques idées, vous me dites ce que vous en pensez : 
D'abord il faudrait une vue principale épurée : ne montrer que les contrôles audio principaux. 
Puis un bouton pour passer en mode multipiste. On aurait alors la liste des pistes et les contrôles pour chaque, plus un bouton pour visualiser le graphe d'ondes pour une seule piste. 
Il faudrait tester, mais je pense pas qu'un Open C soit capable d'afficher plusieurs Canvas à 60fps sur la même page. Dans le meilleur des cas ça mettrait la batterie à genoux, donc il faut les isoler. 

Qu'en pensez-vous ?

**Comment by micbuffa** [comment]
Le truc qui danse en musique c'est la cerise sur le gâteau, ce n'est pas
essentiel, c'est juste pour le fun. SI on diminue la taille, ça bouffe peu
je pense... A vous de tester...

**Comment by RRRRRRRRRRR** [comment]
Je suis plutôt d'accord avec ton idée AlexPernot, le coup de faire un lecteur simple dans une première vue et de dévoiler le multi piste sur un bouton me paraît intéressant, ça permettra à ceux qui veulent se servir de l'appli comme simple lecteur de ne pas être surchargé de boutons inutiles.

**Comment by ChaudAnanas** [comment]
Je suis plutôt d'accord avec ton idée AlexPernot, le coup de faire un lecteur simple dans une première vue et de dévoiler le multi piste sur un bouton me paraît intéressant, ça permettra à ceux qui veulent se servir de l'appli comme simple lecteur de ne pas être surchargé de boutons inutiles.

Edit: si vous avez eu une alerte de ce même message avec comme username "RRRRRRRRRRR", c'était moi, mon ancien compte, j'étais log dessus par défaut je n'avais pas fais attention, j'avais perdu le mot de passe.

**Comment by Felours** [comment]
L'idée est bonne. Je suis pour l'interface épurée tel que tu l'a décrite.

**Comment by micbuffa** [comment]
Niveau optimisation il est possible de ne pas dessiner les formes d'ondes
mais de les pré-calculer sois forme d'images. J'ai déjà ça dans la v2. Et
animer une barre qui défile dessus, ça peut être un div, ou ça peut être un
canvas transparent avec juste un trait blanc... à réfléchir. Je suis au
Maroc, je reviens le 2 Février.

**Comment by AlexManga** [comment]
Maquette d'@AlexPernot : 

![maquette_mt5_alex](https://cloud.githubusercontent.com/assets/6113907/5906151/b7131eaa-a595-11e4-90a3-522e3dfaad45.jpg)

**Comment by AlexPernot** [comment]
J'ai fait une maquette au propre avec le logiciel Pencil, tout est exporté en PNG dans le dossier Maquettes. Dites-m'en ce que vous en pensez, les Niçois. :)
