### ISSUE TITLE
création tuto Firefox OS

### ISSUE THREAD

**Issue by romainchalut** [romainchalut/MT5_FirefoxOS#14]
Pour répondre aux exigences du cahier des charges, nous devons créer une page wiki de tuto firefox os.
Le tutoriel regroupera: 
-lancement d'un émulateur firefox os.
- création d'un manifest.
  -test d'application sur émulateur et téléphone.

**Comment by Felours** [comment]
Il faut qu'on se mette d'accord sur l'aspect graphique de la fenêtre. Histoire de faire des pages homogènes.

**Comment by Felours** [comment]
Présentation finie. S'il y a quelque chose à ajouter / Modifier, n'hésitez pas à le dire.
https://docs.google.com/presentation/d/1OTeCmRwHmsvUhnKloxQkjmyfXZl6hEvmQp2rMFWCAkA/edit?usp=sharing

**Comment by romainchalut** [comment]
Présentation ajoutée dans le dossier "Documentation" du projet gitHub.
