### ISSUE TITLE
Adapter au look and feel Firefox OS.

### ISSUE THREAD

**Issue by AlexPernot** [romainchalut/MT5_FirefoxOS#16]
Mozilla propose des [guidelines](https://www.mozilla.org/en-US/styleguide/products/firefox-os) pour créer une application qui ne choque pas visuellement avec le reste de l'OS. Il faudrait donc adapter l'application à ce _look and feel_.

Le plus simple pour ça est de modifier bootstrap-theme.css, ce qui changera tous les éléments bootstrap de l'application.

**Comment by Desiderius77** [comment]
Oui si vous voulez être accepté sur la Market Place ( et il faut viser à l'être ) il faut suivre ces 
guidelines de look and feel.

Si vous modifiez bootstrap-theme.css, pensez à leur faire un retour ( à bootstrap ). Ca les intéressera surement

**Comment by AlexPernot** [comment]
J'ai mergé mes travaux dans master, c'est pas définitif, mais j'ai déjà fait inclus les bonnes polices, fait des ajustements sur les boutons et le slider de progression de la musique en cours. Il reste à faire les différents contextes des boutons bootstrap (success, error) et le layout principal des pages. En effet, les applications natives n'ont pas de marges sur les pages, elles sont en largeur totale.

**Comment by AlexPernot** [comment]
J'ai fait des gros changements de vue dans `player.html`, je vous invite donc à tester ma branche `looknfeel` et à me dire ce que vous en pensez ici avant le merge.

**Comment by romainchalut** [comment]
Nouveau design approuvé et fusionné sur master.
