### ISSUE TITLE
Bug serveur de quoi fixer ici

### ISSUE THREAD

**Issue by micbuffa** [romainchalut/MT5_FirefoxOS#17]
J'ai corrigé un bug serveur sévère aujourd'hui dans le cas où on appelle le web service avec /track suivi d'un nom de track qui n'existe pas. J'ai commité mes changements sur server.js.
Est-ce vous qui avez souvent crashé mt5demo.gexsoft.com ? J'ai fini par tracer et identifier le cas qui faisait tout planter. Quelqu'un utlisait le web service track/nom_track avec des noms mal formés (double quote au début et pas de double quote fermante"). Si c'est vous il y a ou il y a eu un bug qq part dans le client ou dans la manière dont vous essayez d'accéder aux chansons.

Michel

**Comment by AlexPernot** [comment]
Bonjour,

Non c'est pas nous, on travaille qu'en local. :) 
On fera un rebase pour intégrer le correctif, merci !
