### ISSUE TITLE
Séparer la partie serveur de la partie client

### ISSUE THREAD

**Issue by AlexManga** [romainchalut/MT5_FirefoxOS#18]
A terme l'application ne doit pas embarquer Node.JS et les tracks de musique (ou une/deux pour l'exemple). 
Il faudra faire deux parties distinctes qui décriront comment installer d'une part l'application sous FxOs et d'autre part installer un serveur "MT5" avec node.js.

**Comment by romainchalut** [comment]
Création d'une branche avec nouvelle organisation des dossiers (branche : issue#18)

**Comment by romainchalut** [comment]
Pour lancer le serveur il faut se placer dans le dossier server en ligne de commande puis  :  "node server.js".
Le manifest pour l'application firefoxOS a changé de place, il est dans le dossier client maintenant.
