### ISSUE TITLE
Créer un page de selection de la musique sur serveur distant

### ISSUE THREAD

**Issue by romainchalut** [romainchalut/MT5_FirefoxOS#20]
Mise en forme du catalogue serveur

**Comment by AlexPernot** [comment]
Après discussion avec Romain, on pense que plutôt créer une autre page de sélection, on peut intégrer ça à la vue du player. Ma proposition, [visible sur ce jsbin](http://jsbin.com/sojunaqaza) : 

Lorsqu'on clique sur un bouton "Ouvrir...", une liste à deux onglets apparaît, avec un onglet local, et un onglet serveur. Comme ça, après la connexion initiale, on abstrait totalement les aller-retours avec le serveur pour l'utilisateur (sauf pour les temps de chargement bien sûr).

Qu'en pensez-vous ?

**Comment by ChaudAnanas** [comment]
Je trouve ça bien

**Comment by AlexPernot** [comment]
Finalement ça a été fait dans l'issue #19, donc je ferme ici.
