### ISSUE TITLE
Correction bugs divers & dernières améliorations

### ISSUE THREAD

**Issue by romainchalut** [romainchalut/MT5_FirefoxOS#22]
- Remise à zéro des sliders.
- Cache des boutons de lecture si musique non chargée.
- Différenciation de la liste local et serveur.

**Comment by AlexManga** [comment]
J'ajouterais aussi : 
- validation du manifest,
- creation icone 128px

Je crée la branche Issue#22 depuis la branche issue#19

**Comment by romainchalut** [comment]
Il faudrait aussi : 
- rechargement de la liste des musiques locale

**Comment by AlexManga** [comment]
- Création d'une méthode différente pour le chargement d'une musique en local et sur le serveur
- Indicateur pour savoir quelle musique est jouée (couleur, icone, titre ? dans le tableau ? )

**Comment by AlexManga** [comment]
Commit réalisé sur la branche issue#22 (oublié de le référencer dans le message de commit) avec ces modifs : 
- Ajout d’une temporisation sur le bouton play pour ne pas cliquer
  dessus lorsque la musique charge.
- Meilleure gestion des tableaux en haut de page
- Passage en « active » de l’item actif (current song)
- Ajout du titre de la musique jouée
- Correction de la mise a jour des temps quand le slider (simple) est
  bougé a la main
- Correction du chemin de l’icone dans le manifest
- Ajout d’une fonction qui permet de jouer les musiques MT5 en local
- Mise en commentaire de l’affichage des musiques présentes sur le
  téléphone (on ne sait pas les jouer directement pour le moment, a faire)

**Comment by AlexManga** [comment]
- Ignorer les dossiers dans la liste des musiques locales

**Comment by AlexManga** [comment]
Fin des développements pour cette issue.
Merge avec Master terminé avec succès. L'issue peut être fermée.
