### ISSUE TITLE
Ne pas avoir la possibilité de se connecter si absence de réseau

### ISSUE THREAD

**Issue by AlexManga** [romainchalut/MT5_FirefoxOS#23]
- Sur la page d'initialisation, tant que le téléphone est déconnecté, il ne sera pas possible de saisir des informations dans les champs serveur/port
  -> évite de perdre du temps pour l'utilisateur

**Comment by Felours** [comment]
Fonctionnalité ajoutée.
Testé sur le Flame en wifi et sur 3g (s'il vous plait si vous pouvez tester aussi sur le votre pour voir s'il fonctionne correctement sur 3g).

J'ai également modifié le comportement du clic sur le bouton de connexion en cas où aucune connexion réseau est possible.

**Comment by AlexManga** [comment]
Super merci, tu as travaillé sur quelle branche ?
De notre coté, nous n'avons pas la possibilité de mettre une carte sim dans notre mobile donc on testera seulement en wifi.

**Comment by Felours** [comment]
Justement il me semble que vous avez dit que la branche master aura les modifications les plus mises à jour, et puisque l'interface ressemble à celle que vous avez montré hier en demo alors j'ai fait une branche de celle-ci (master) en l’appelant Issue#23.

**Comment by AlexManga** [comment]
C'est parfait ! :) L'équipe se tiendra au courant si quelqu'un teste cette issue.
Après validation d'une ou deux personnes (mini) tu pourras ajouter tes modifs à la branche master ("merge")

**Comment by Felours** [comment]
Pas de soucis :)

Je tiens à signaler que le test sur la 3g (et le wifi bien sûr) est passé chez moi (avec une carte du membre de la famille car la mienne n'était pas reconnue), donc normalement c'est fonctionnel avec les deux.

**Comment by romainchalut** [comment]
Je n'arrive pas à tester sur l'émulateur. 
Même en mode en avion il n'y a pas de changement .
Alexis tu pourras test avec le flame ??

**Comment by micbuffa** [comment]
Comment vous testez le fait qu'on est online ou pas. Attention, navigator.online ne fonctionne pas bien sur firefox... La vraie "bonne manière" consiste à : 1) tester si navigator.online est off, dans ce cas oui, on est offline, 2) si on est "on", il faut envoyer une requête ajax au serveur et voir si il répond. On peut être online sur le réseau et avoir un serveur down, un DNS qui ne répond pas etc. Ce n'est pas si simple de détecter qu'on est online.... cf ce que fait gmail

**Comment by romainchalut** [comment]
Merci de l'astuce mais nous faisons  notre test sur la page d’initialisation (qui ne sera plus présente sur le marketPlace) du coup, nous ne pouvons pas interroger le serveur car il n'est pas encore renseigné.

**Comment by Desiderius77** [comment]
C'est interdit la fessée ! Pauvre test sur la page d’initialisation  !

**Comment by romainchalut** [comment]
Sur le reste de l'application des tests sont déjà présents. Cette issue couvre seulement le comportement de la page d'initialisation !

**Comment by romainchalut** [comment]
A oui désolé pas compris la blague de suite, comme j'ai corrigé la faute entre temps ^^

**Comment by Felours** [comment]
Je viens de vérifier.
En effet le simulateur ne détecte pas l'état de la connexion avec navigator.online, mais sur le portable la détection se fait correctement.

Sachant que ce qu'on souhaite vérifier ce n'est pas l'état du serveur en lui même, mais l'état de la connexion réseau du mobile, on ne peut pas utiliser le serveur d'application (car c'est une étape précédente au connexion serveur).

**Comment by AlexPernot** [comment]
Petite précision : on veut savoir si le device peut se connecter au serveur ou pas, la cause n'importe pas, que ce soit le serveur qui répond pas ou le mobile qui capte pas, c'est pas le problème de l'appli. :)

**Comment by Felours** [comment]
Attends. Vous voulez du coup que la vérification se fasse non plus par rapport à l'état du réseau mais par rapport au serveur de connexion?

**Comment by Felours** [comment]
C'est dans quelle issue que la connexion au serveur a été faite?

**Comment by romainchalut** [comment]
il n'y a pas de connexion serveur à proprement parlé juste des requetes envoyées

**Comment by Felours** [comment]
Oui. Mais du coup on ne doit plus traiter l'état du réseau? L'objet de l'issue était au départ le traitement d'une vérification afin d'empêcher une personne d'entrer des coordonnées alors qu'aucune connexion est possible au niveau du réseau (absence de wifi/3G).

**Comment by romainchalut** [comment]
Si c'est le sujet de l'issue, empêcher de renseigner les champs de connexion si aucun réseau n'est disponible.

**Comment by Felours** [comment]
Je parlais de la vérification de la disponibilité du serveur, pas de la vérification de la disponibilité d'un réseau (qui est déjà fait).

**Comment by romainchalut** [comment]
merge avec master ok
