### ISSUE TITLE
Créer le manuel de publication sur la MarketPlace Firefox OS

### ISSUE THREAD

**Issue by romainchalut** [romainchalut/MT5_FirefoxOS#24]
Une fois l'application  terminé, il faudrait la poster sur le marketplace .
Pour cela plusieurs conditions sont à remplir.
Ce manuel recensera les différentes conditions de publication sur le marketplace.

**Comment by ChaudAnanas** [comment]
Je prends ça pour vendredi + samedi

**Comment by ChaudAnanas** [comment]
Voilà le document : 

https://docs.google.com/presentation/d/1Mtm86MdSh-WbgoDnUUGVtC1wWi3xAY29SfdngVWkQqk/edit?usp=sharing

**Comment by AlexPernot** [comment]
Pas mal du tout ! Tu peux le commit sur master.

**Comment by micbuffa** [comment]
Très bien. Je me demandais si il n'était pas nécessaire d'avoir une
application multi-langues et dans ce cas, comment on s'y prend. Est-ce
qu'il y a des outils, des recommandations, etc. Pour android il y a des
"resources bundles" pour stocker les messages dans plusieurs langues, mais
là, avec une appli web ?

2015-03-15 9:18 GMT+01:00 Alex Pernot notifications@github.com:

**Comment by micbuffa** [comment]
Très bien. Je me demandais si il n'était pas nécessaire d'avoir une application multi-langues et dans ce cas, comment on s'y prend. Est-ce qu'il y a des outils, des recommandations, etc. Pour android il y a des "resources bundles" pour stocker les messages dans plusieurs langues, mais là, avec une appli web ?

**Comment by ChaudAnanas** [comment]
@micbuffa En fait, du moment que l'application est disponible dans les langues décrites dans le manifest (les "locale keys"), c'est bon. Mais j'ai effectué le processus avec une app de test dans laquelle il n'y avait pas cette ligne dans le manifest et ça a passé le processus de validation, donc il n'est pas obligatoire de localiser son application.
Par contre si on souhaite le faire il y a un tuto ici : https://developer.mozilla.org/en-US/Firefox_OS/Developing_Gaia/Localizing_Firefox_OS
Je peux le rajouter dans le document si vous voulez.

@AlexPernot tu veux que je mettes ça à la racine du projet ? dans un dossier /documents ? je le mets en PDF ?

**Comment by romainchalut** [comment]
OK document déposé dans le dossier "documents" à la racine du projet github.

**Comment by romainchalut** [comment]
Page wiki crée.
