### ISSUE TITLE
Développer un menu "About" (à propos)

### ISSUE THREAD

**Issue by AlexManga** [romainchalut/MT5_FirefoxOS#28]
Ce menu devra comporter les éléments suivants :
- Noms des contributeurs de l'applications (enseignants compris) avec leurs comptes GitHub
- Version de l'application
- Détails et liens (?)

Ceci est à intégrer au menu général de l'application présent dans le player (voir issue #29)

**Comment by Felours** [comment]
Ce menu doit être accessible de quelle façon? 
Puisque sur les portables Firefox OS il n'y a pas de boutons latéraux comme sur les portables Android, on ne peut pas afficher un menu caché par clic gauche. Doit il être accessible via la page elle même? Ce que tu appelles IHM du player c'est la page des musiques?

**Comment by AlexManga** [comment]
Ce menu doit être intégré dans le menu de préférences (voir issue #29) 
L'IHM du player est celle qui contient effectivement les musiques, les boutons play etc. 
Je vais modifier le premier post pour préciser qu'il faut qu'il soit intégrer au menu général.

Regarde du coté des menus dans bootstrap mais ici il suffit, je pense, de faire une sorte de pop up ou un div qui sera affiché par dessus la page active et elle disparaitra par clic sur l'exterieur ou grace à une X sur la fenetre.

**Comment by Felours** [comment]
Je vois, merci beaucoup :)
Vais m'y mettre si personne ne s'est mis déjà.

**Comment by AlexManga** [comment]
Non tu peux t'y assigner, merci :+1:

**Comment by AlexPernot** [comment]
J'ai posté dans #29 pour donner quelques pistes pour tes questions d'ergonomie plus haut. IMO je pense que c'est mieux de faire le menu de préférences complet avant, même si les items sont inactifs pour l'instant, puis faire le About.

**Comment by AlexManga** [comment]
Il serait bien que l'apparence de ce menu respecte l'apparence des autres menus déjà développés (ils sont présents dans la branche master si tu veux tester). C'est à dire une pop up bootstrap avec les informations demandées et un bouton Fermer.

**Comment by Felours** [comment]
Je viens de finir le menu. Pouvez vous le regarder afin de déterminer s'il est à votre goût (et sinon, quoi changer et en quoi).

**Comment by romainchalut** [comment]
Menu ok , code merge avec master.

**Comment by micbuffa** [comment]
Je peux le voir ? screenshot ?

**Comment by romainchalut** [comment]
Voici les screenshots :

![image](https://cloud.githubusercontent.com/assets/7162251/6652933/2c14af3e-ca80-11e4-9f84-3571c68a78b6.png)

![image](https://cloud.githubusercontent.com/assets/7162251/6652926/1bdf11e0-ca80-11e4-8e4c-14416ffb3738.png)
![image](https://cloud.githubusercontent.com/assets/7162251/6652929/23541b82-ca80-11e4-98fe-c9a8df63951b.png)

**Comment by micbuffa** [comment]
Super :-) Vous avez fait le soft en un seul langage ? Vous affolez pas, ne
changez rien maintenant, mais est-ce que vous avez vu quelque part la
manière conseillée de faire un soft multi-lingue ?

2015-03-14 19:28 GMT+01:00 Romain Chalut notifications@github.com:
