### ISSUE TITLE
Développer un menu de préférences 

### ISSUE THREAD

**Issue by AlexManga** [romainchalut/MT5_FirefoxOS#29]
Ce menu devra comporter :
- Savoir si on veut ou non enregistrer automatique la musique depuis le serveur ?
- Changer l'adresse du serveur auquel on est connecté (à terme il y aura un serveur par défaut qu'on pourra modifier ici)
- lien vers le menu about (voir issue #28)

**Comment by AlexPernot** [comment]
La vraie problématique ici, ça va être de savoir comment accéder à ce fameux menu. Il faut que l'accès soit intuitif, et non intrusif pour le reste de l'application. [Ce lien est un début de piste](https://www.mozilla.org/en-US/styleguide/products/firefox-os/headers).

Le mieux reste de voir comment c'est géré dans les autres applications de base du système. Vous embêtez pas pour le style avancé (positionnement des titres, dégradés du background, etc), je m'en occuperais après. :)

**Comment by Felours** [comment]
Ce que je ne comprends pas trop c'est le lien vers le menu about. Un clic sur ce lien va afficher le menu about de quelle façon?

Alex la solution proposée me semble pas mal. Sur le téléphone qu'on a l'application d'agenda a le même, avec un menu déroulant en plus. Toutefois ce menu déroulant se déroule sur la majeure partie de l'application (un clic supplémentaire le renferme).

**Comment by Felours** [comment]
J'ai fait un mixt entre le header qu'Alex a proposé et un menu déroulant fait en bootstrap. Je l'upload pour que vous puissiez voir si c'est un genre de menu qui pourrait vous intéresser.
J'ai juste mis 3 liens vides pour le moment, mais ça suffit pour montrer l'aspect graphique.

**Comment by romainchalut** [comment]
c'est sympa par contre je trouve le texte un peu écrasé dans le menu.

**Comment by AlexManga** [comment]
Même remarque que Romain, il faut penser que ce sont des doigts qui vont appuyer dessus et ici il est facile de taper à coté. 
Je viens de voir le menu de l'application Calendar et en effet ce menu est très sympa et il y a la place pour les textes.

De plus la zone de clic du menu n'est pas assez large contrairement à celle du calendar :

![2015-03-05_09h08_52](https://cloud.githubusercontent.com/assets/6113907/6501361/8f0a1e1e-c317-11e4-82d2-60b42caa2f44.png)
![2015-03-05_09h09_08](https://cloud.githubusercontent.com/assets/6113907/6501362/8f0e4098-c317-11e4-8808-14c15b1bebf5.png)

Mais well done :)

**Comment by Felours** [comment]
Modifications apportées.
Cela vous convient ou il faut changer des trucs?

**Comment by AlexManga** [comment]
Super je viens de tester sur le téléphone et la navigation est confortable. Les zones de clic sont assez grandes. Parfait moi j'dis  :+1: 
Enfin... juste les libellés si on peut trouver autre chose de plus parlant. A vos propositions !

**Comment by AlexPernot** [comment]
Je propose : 

"Configuration enregistrement auto" => Paramètres mode hors ligne...
"Changement d'adresse" => Paramètres connexion...
"About" => À propos...

**Comment by romainchalut** [comment]
Voici mes propositions :
![capture](https://cloud.githubusercontent.com/assets/7162251/6543372/78a85eac-c519-11e4-9f14-c195c7852792.JPG)

**Comment by romainchalut** [comment]
Pour le cache, je pensais à un choix de mise en mémoire en fonction du type de connexion (cellulaire ou WIFI).

**Comment by AlexManga** [comment]
Le libellé "Paramètre de cache" ne veut rien dire pour un utilisateur lambda. Plutôt mettre "Paramètre d'enregistrement" où l'on pourrait ajouter (plus tard) les paramètres liés à l'enregistrement de mix sur le téléphone par exemple. Sinon pour les deux autres je suis d'accord.

**Comment by Felours** [comment]
Modification prises en comptes et synchronisées.

**Comment by romainchalut** [comment]
merge avec master ok
