### ISSUE TITLE
Paramétrage serveur et port

### ISSUE THREAD

**Issue by AlexPernot** [romainchalut/MT5_FirefoxOS#3]
Actuellement, le client se connecte au serveur de M. Buffa (adresse IP+port hardcodés). Il faut pouvoir choisir sur quel serveur on se connecte. Pour cela, deux choses à faire : 
- Dans la **page d'initialisation**, il faut faire un formulaire qui va se connecter (en AJAX) au serveur spécifié.
- Dans le **serveur Node.js**, il faut pouvoir accepter les connexions entrantes (peut être qu'il n'y a rien à modifier, j'ai pas regardé le code du serveur).

**Comment by romainchalut** [comment]
fin de l'issue branche issue#3
