### ISSUE TITLE
Gérer la suppression des musiques téléchargées

### ISSUE THREAD

**Issue by AlexManga** [romainchalut/MT5_FirefoxOS#30]
Il doit être possible de supprimer les musiques téléchargées depuis le serveur directement depuis l'application sans passer par le branchement au PC etc. (par swipe dans la liste peut être ? ou menu a part)

**Comment by ChaudAnanas** [comment]
Normalement c'est bon, ça fonctionne sur le ZTE en tout cas.
- Swipe pour supprimer une musique de la liste des musiques en local
- Boîte de dialogue pour confirmer la suppression
- Refresh de la page pour mettre à jour la liste des musiques

Bugs : 
- La 1ere fois qu'on supprime une musique, l'application demande l'autorisation d'accès à la carte mémoire, ça fait +/- échouer le refresh, la musique apparaîtra toujours dans la liste mais elle sera quand même effacée de la carte sd. SI on autorise l'application à accéder à la carte sd et qu'on demande à ne plus recevoir le message, ce bug ne se produit plus
- Sur simulateur, ça fonctionne bizarrement...
  - Les musiques en local sont celles de C:\Users\Username\Music\MT5
  - Les musiques effacées sont celles de la fake carte SD dans C:\Users\Username\AppData\Roaming\Mozilla\Firefox\Profiles\kuxxcefx.dev-edition-default\extensions\fxos_2_2_simulator@mozilla.org\profile\fake-sdcard\MT5
  - Quand on supprime une musique sur l'application, cela va supprimer la musique dans la fake carte SD donc ça ne la supprime pas de C:\Users\Username\Music\MT5 donc elle reste dans la liste
  - Le moyen le plus "simple" pour tester que j'ai trouvé, c'était de mettre les mêmes musiques dans les 2 endroits (à la main), de regarder le dossier de la fake carte SD quand on supprime une musique sur l'application et de constater sa suppression

**Comment by romainchalut** [comment]
OK, pour le test sur émulateur si on se place dans le dossier  fake-sdcards. 
Pour le refresh, il faut le faire dans le  onsuccess du delete car sinon il y a une désynchronisation.
Et regarde si tu ne peux pas recharger seulement la liste, pas toute la page car c'est un peu lourd comme technique, tu peux par exemple utiliser la méthode loadSongListLocal().
La suppression doit  être possible que sur les musiques MT5 pas le reste pour éviter de toucher les musiques personnelles de l'utilisateur.

**Comment by ChaudAnanas** [comment]
- La suppression n'est maintenant possible que sur les musiques MT5
- Le refresh j'ai try des trucs (que j'ai laissés en commentaires) pour refresh uniquement la bonne div mais rien n'a fonctionné, quand je passais par le débogueur pour regarder quelle partie était refresh, j'avais l'impression que cette ligne fonctionnait mais quand je faisais le test en réel, ça ne fonctionnait pas :
  - $("#listeMusique").load(location.href);

**Comment by romainchalut** [comment]
J'ai commit une solution pour faire le refresh seulement sur la liste .
Il fallait faire un callback qui appelait la méthode loadSongListLocal() sinon il y a un problème de non déclaration car player.js est défini  après persist.js

**Comment by AlexManga** [comment]
J'ai testé sur le Flame et ça fonctionne une fois de temps en temps (je pense que c'est la réactivité du téléphone). Et le refresh du div ne se fait pas, je dois recliquer sur le bouton parcourir pour que ce soit bon.
Par contre il serait bien d'avoir un "hint" (une astuce en premier plan sur fond flou) qui précise qu'il est possible de pouvoir supprimer ces musiques à l'utilisateur.

**Comment by ChaudAnanas** [comment]
sur le ZTE ça marche parfaitement et ok pour l'astuce

**Comment by Felours** [comment]
Je confirme. Sur la Flame la suppression se fait correctement également.

**Comment by romainchalut** [comment]
Issue 30 merge dans master
