### ISSUE TITLE
Développer la configuration du changement de serveur

### ISSUE THREAD

**Issue by Felours** [romainchalut/MT5_FirefoxOS#31]
La vue doit contenir les paramètres serveurs (adresse + port) qu'on peut modifier.

Cette vue sera accessible en appuyant sur le lien se trouvant dans le menu développé dans l'Issue #29.

Une fois modifiés, on doit pouvoir changer de connexion vers le serveur souhaité (en cliquant sur un bouton "Connecter"). 

On doit pouvoir fermer la vue, par exemple en appuyant sur un bouton.

**Comment by Felours** [comment]
Je propose que la vue soit sur une division cachée qui sera accessible (via l’élément CSS 'display') une fois qu'on clic sur le lien du menu.

**Comment by AlexManga** [comment]
Pour tout ce qui est préférences, sauvegarde de configuration il faut voir du coté du local storage, un tuto est dispo à cette [adresse](http://rominirani.com/2013/08/01/firefox-os-tutorial-episode-6-enabling-storage/).

**Comment by romainchalut** [comment]
Je pense que la vue d'initialisation va migrer pour devenir cette page.

**Comment by romainchalut** [comment]
Modification merge sur master.
