### ISSUE TITLE
Créer une page d'aide

### ISSUE THREAD

**Issue by romainchalut** [romainchalut/MT5_FirefoxOS#32]
Elle devra contenir :
-une aide sur la vue (explication des boutons).
-liste de scénarios basiques d'utilisations. 

Et sera accessible a tout moment.

**Comment by Felours** [comment]
Dans notre dossier à rendre nous avons fait une description du fonctionnement de l'application (Version web et version Firefox OS).

Cette explication inclut avec des captures d’écran.
Voici le lien vers le document Google doc.
https://docs.google.com/document/d/1ewCNFdPT6u2Q-dMqOELbhIUncQAIlVTKz_SuOi20YvI/edit?usp=sharing

**Comment by micbuffa** [comment]
Attention aux très nombreuses fautes d'orthographe. J'aurais pu en corriger une trentaine rien qu'en relisant... mettez moi en read/write et didier aussi si vous voulez qu'on le fasse à la volée...

**Comment by micbuffa** [comment]
N'oubliez un super menu "About" avec le lien vers le github et le lien vers la page d'aide. Qu'on puisse savoir qui a fait ce logiciel, etc... vendez-vous. Aussi, le repository est un fork, mais le README est demeuré le même, ce qui induit les gens en erreur. Il y en a un qui a débarqué et qui posse des questions car il utilise le soft (la version web) pour sa chorale, et il demande des fonctionnalités supplémentaires etc... Corrigez mon readme et indiquez le but du fork. Ce serait bien aussi de faire le ménage dans les branches vers la fin du projet, qu'il ne reste plus que la version FF OS. Didier qu'en penses-tu ?

**Comment by AlexManga** [comment]
La page d'aide ne sera pas une doc complète comme celle-ci non plus. Je ne l'ai pas encore lu mais j'ai vu que je ne pouvais pas la modifier non plus. Je pense que je vais prendre cette issue.
Je suis aussi d'accord avec @micbuffa pour modifier le github. Je crée l'issue là dessus.

**Comment by Felours** [comment]
J'ai modifié les droits d'accès et le document peut être modifié.
On va corriger les fautes :)

**Comment by Desiderius77** [comment]
Tout à fait d'accord avec @micbuffa !
Vous en êtes à un point de votre projet où il faut "clarifier les choses" : README correcte et explicite
( pour éviter l'erreur de version ): sources clairs et réduction ( merge ) des branches .
Attention avant tout à l'orthographe ! Cela peut rebuter directement des utilisateurs potentiels !

Et puis ne faudrait il pas trouver un nkom plus explicite que "MT5" pour attirer aussi les utilisateurs ?

**Comment by AlexManga** [comment]
Une issue a été crée pour parler de ce sujet (issue #35).
Je copie votre message dans l'issue.

**Comment by AlexManga** [comment]
Je propose un template d'astuce comme celui utilisé dans le calendar : 

![capture d ecran 2015-03-09 a 17 21 59](https://cloud.githubusercontent.com/assets/6113907/6559088/d3389c0c-c680-11e4-934b-b35fbe6dfdba.png)

Pour la page d'aide, l'idée serait de réunir toutes ces astuces ou de faire des gifs pour que ce soit plus parlant ?

**Comment by AlexPernot** [comment]
Terminé et mergé dans master.
