### ISSUE TITLE
Adjust start offset for tracks?

### ISSUE THREAD

**Issue by mrjcleaver** [romainchalut/MT5_FirefoxOS#34]
Hi,

So, I'm in a choir - MT5 is going to be very handy for practice. Thanks!

Question: is there a way to adjust the offset start time for each track?

If you pick the last song on http://confluence.newchoir.ca:3000 you'll see that the start time of the 3 tracks I uploaded is slightly off. I'd want a way to nudge them into sync.

Cheers,
   Martin.

**Comment by micbuffa** [comment]
Can you explain? 

I kept mt5 as simple as possible, you should sync your files with audacity before publishing them in mt5...

**Comment by micbuffa** [comment]
Also, you are on a fork of the original MT5 that is at: https://github.com/squallooo/MT5

This fork is for the FireFox OS version of MT5.

**Comment by mrjcleaver** [comment]
Well, the tracks get contributed into SoundCloud from various sources, and our choir members are very non-technical so Audacity is hard for them.

We're trying to decentralize as much as possible (we have 150 people in the choir - coordination is hard). So, for us, the more we have in the end user tools the better.

I knew I was on a fork (I selected the most recently updated fork intentionally), but I didn't realize this fork had a different intent: that wasn't reflected in the description. Does that explain why sometimes I get redirected to blob:http://confluence.newchoir.ca:3000/b7ea6076-d9ef-4ec2-9be5-91aa3f2db37b ?

Thanks, M.

**Comment by micbuffa** [comment]
Ok what would you imagine as a graphic user interface for doing what you
need? Detail as much as possible please... I'll see if I can help...
