### ISSUE TITLE
Finaliser le projet GitHub

### ISSUE THREAD

**Issue by AlexManga** [romainchalut/MT5_FirefoxOS#35]
Pour ne pas induire les gens en erreur et pour les futurs contributeurs du projet il est nécessaire de : 
- d'adapter le Readme du github du projet en fonction de la nouvelle application (bien séparer la partie serveur et cliente)
- faire le ménage dans les branches pour n'avoir que la branche master à jour (à faire lorsque les derniers développements seront validés par des tests)

**Comment by AlexManga** [comment]
Message de @Desiderius77 : 
Tout à fait d'accord avec @micbuffa !
Vous en êtes à un point de votre projet où il faut "clarifier les choses" : README correcte et explicite
( pour éviter l'erreur de version ): sources clairs et réduction ( merge ) des branches .
Attention avant tout à l'orthographe ! Cela peut rebuter directement des utilisateurs potentiels !

Et puis ne faudrait il pas trouver un nkom plus explicite que "MT5" pour attirer aussi les utilisateurs ?

**Comment by AlexPernot** [comment]
Personellement, j'aime bien MT5, ça décrit très bien l'application : multitrack en html5. Je propose le nom MT5 Fx pour ce fork, qu'en pensez-vous ?

Je vais corriger le README, en prenant en compte la scission qui a été faite entre client et serveur.

**Comment by Desiderius77** [comment]
Oui mais parce que vous savez ce que cela signifie !

"Multitrack HTML5 Player" parlera à toute le monde  alors que MT5 ?

**Comment by AlexPernot** [comment]
Le nom complet est bien trop long pour être affiché dans un contexte d'application mobile.

Et puis quel utilisateur lambda sait ce que signifie VLC, GTK, GIMP ou même UNIX ? :)

**Comment by Desiderius77** [comment]
Nous ne nous comprenons pas .

OK pour MT5 dans votre interface spécialement sur mobile, ....

C'est sur la page Github  ( README.md par exemple ) que je trouve qu'il serait intéressant d'avoir le nom complet

**Comment by AlexPernot** [comment]
Il est sur la première ligne du Readme, en <h1> : MT5 - A multitrack HTML5 Player

**Comment by AlexPernot** [comment]
README mis à jour sur master (et donc sur la page GitHub).

**Comment by romainchalut** [comment]
Les branches liées aux issues fermés sont supprimées.

**Comment by mrjcleaver** [comment]
![mt5 2015-03-09 10-07-20](https://cloud.githubusercontent.com/assets/59202/6556466/1d3df596-c644-11e4-91bc-4e9a155d0133.png)

**Comment by mrjcleaver** [comment]
And per https://github.com/romainchalut/MT5/issues/34#issuecomment-77754366 : 

![mt5 2015-03-09 10-11-52](https://cloud.githubusercontent.com/assets/59202/6556588/dce0e21e-c644-11e4-9d5a-c1057bd17f7c.png)

**Comment by AlexPernot** [comment]
Sounds good to me, anyone else like it ?

**Comment by romainchalut** [comment]
The repository is renamed into MT5_FirefoxOS

**Comment by romainchalut** [comment]
Mettre à jour le readme (suppression de la partie canvas et modification partie cliente)
