### ISSUE TITLE
Activer ou non le téléchargement automatique des musiques depuis le serveur

### ISSUE THREAD

**Issue by AlexManga** [romainchalut/MT5_FirefoxOS#36]
En lien avec l'issue #29, un menu doit être accessible depuis les préférences de l'application pour permettre à l'utilisateur de choisir s'il veut ou non permettre le téléchargement en local des musiques depuis le serveur.
Niveau IHM : pop up avec une case a cocher ou un slider (comme pour activer/désactiver le wifi par ex)
Le choix de la pop up est principalement du au fait qu'il y a très peu d'informations à afficher (juste un libellé et une action)

**Comment by romainchalut** [comment]
merge avec master
