### ISSUE TITLE
Vue générale : faire les contrôles audio

### ISSUE THREAD

**Issue by AlexPernot** [romainchalut/MT5_FirefoxOS#4]
Doit contenir les fonctions : 
- Musique précédente
- Musique suivante
- Mettre en pause/reprendre la musique
- Probablement le plus dur, une barre de progression pour la musique, avec possibilité de cliquer n'importe où sur la barre pour "sauter" jusqu'à cette partie de la musique

**Comment by AlexManga** [comment]
Je prends !

**Comment by AlexManga** [comment]
Pas de bouton pour la musique suivante/précédente mais plutôt parcourir (pour chercher une autre musique) et enregistrer le mix effectué.
Je vais merger mes travaux sur la branche master.
