### ISSUE TITLE
Poster l'application sur le marketPlace Firefox OS

### ISSUE THREAD

**Issue by romainchalut** [romainchalut/MT5_FirefoxOS#42]
L'application doit être postée sur le marketPlace Firefox OS en se basant sur le guide crée  dans le cadre de l'issue #24 . 
Tout en répondant aux normes de sécurité fixées par Mozilla.

**Comment by AlexPernot** [comment]
Application postée, la fiche se trouve [ici](https://marketplace.firefox.com/app/mt5/) mais ne sera sûrement pas visible par le public avant l'approbation par Mozilla (estimée par eux à 6 jours ouvrés).
