### ISSUE TITLE
Vué générale : faire les contrôles de boucle

### ISSUE THREAD

**Issue by AlexPernot** [romainchalut/MT5_FirefoxOS#5]
Doit contenir les boutons suivants : 
- Poser le début de boucle
- Poser la fin de boucle
- Activer/désactiver le mode boucle
- Revenir au début de boucle

Bonne chance pour trouver des icones parlantes. :)

**Comment by romainchalut** [comment]
@AlexManga  a refait le système de boucle suite au performance de notre téléphone de test (2 secondes de latence après le clic sur le bouton ...). Une solution utilisable quand la musique est en pause et non lancée.
