### ISSUE TITLE
Vue générale : bouton du mode multipiste

### ISSUE THREAD

**Issue by AlexPernot** [romainchalut/MT5_FirefoxOS#6]
Idéalement situé en bas de l'écran, permet d'activer/désactiver l'affichage des différentes pistes.

Suite à la réunion du 01/02/2015, il a été décidé que les pistes remplaceraient la pochette d'album lors de l'appui sur le bouton, afin qu'elles occupent la majeure partie de l'écran.

**Comment by AlexManga** [comment]
Implémentation du bouton, RAF : la liste des pistes à la place de l'image de l'album (voir maquettes)
