### ISSUE TITLE
Créer  plan de tests Fonctionnel

### ISSUE THREAD

**Issue by romainchalut** [romainchalut/MT5_FirefoxOS#8]
Pour vérifier le bon fonctionnement de l'application, un plan de tests doit être rédigé.
Il couvrira l'intégralité des fonctionnalités proposées.

**Comment by romainchalut** [comment]
Je rédige le plan de test par contre j’aimerai avoir une version stable de merge pour mardi sur master, pour commencer les tests.

**Comment by romainchalut** [comment]
Plan de tests fonctionnel crée, déroulement prévu demain.

**Comment by romainchalut** [comment]
liste des tests renseignée dans le wiki : https://github.com/romainchalut/MT5_FirefoxOS/wiki/Liste-des-tests-fonctionnels-r%C3%A9alis%C3%A9s

**Comment by micbuffa** [comment]
Très bien tout cela. Il me tarde de voir la version finale :-)
